import { namenZijnGelijk } from "@/lib/namen";
import type { HistorischeSpelerStand, HistorischeTussenstand } from "@/types/competition";

/**
 * Officiële tussenstand seizoen 2025/2026 (bron: foto 15-08-2026).
 * Waarden zijn historisch en mogen niet opnieuw worden berekend.
 */
export const OFFICIELE_TUSSENSTAND_2025_2026: HistorischeTussenstand = {
  seizoen: "2025-2026",
  datum: "2026-08-15",
  bron: "Officiële tussenstand 15-08-2026",
  spelers: [
    {
      positie: 1,
      naam: "John Wolsheumer",
      aanwezig: 30,
      poulepunten: 117,
      winnaarsrondeLegsGewonnen: 295,
      winnaarsrondeLegsVerloren: 82,
      verliezersrondeLegsGewonnen: 0,
      verliezersrondeLegsVerloren: 0,
      hoogsteFinish: 145,
      aantal180s: 77,
      puntenTotaal: 599,
    },
    {
      positie: 2,
      naam: "Nico Pas",
      aanwezig: 32,
      poulepunten: 105,
      winnaarsrondeLegsGewonnen: 166,
      winnaarsrondeLegsVerloren: 112,
      verliezersrondeLegsGewonnen: 13,
      verliezersrondeLegsVerloren: 3,
      hoogsteFinish: 121,
      aantal180s: 10,
      puntenTotaal: 338.5,
    },
    {
      positie: 3,
      naam: "Toon te Kamp",
      aanwezig: 23,
      poulepunten: 85,
      winnaarsrondeLegsGewonnen: 117,
      winnaarsrondeLegsVerloren: 88,
      verliezersrondeLegsGewonnen: 7,
      verliezersrondeLegsVerloren: 1,
      hoogsteFinish: 148,
      aantal180s: 13,
      puntenTotaal: 266.5,
    },
    {
      positie: 4,
      naam: "Ronnie Kijvekamp",
      aanwezig: 35,
      poulepunten: 92,
      winnaarsrondeLegsGewonnen: 67,
      winnaarsrondeLegsVerloren: 76,
      verliezersrondeLegsGewonnen: 57,
      verliezersrondeLegsVerloren: 24,
      hoogsteFinish: 112,
      aantal180s: 3,
      puntenTotaal: 241.5,
    },
    {
      positie: 5,
      naam: "Rinaldo Lenting",
      aanwezig: 17,
      poulepunten: 57,
      winnaarsrondeLegsGewonnen: 86,
      winnaarsrondeLegsVerloren: 58,
      verliezersrondeLegsGewonnen: 9,
      verliezersrondeLegsVerloren: 6,
      hoogsteFinish: 160,
      aantal180s: 18,
      puntenTotaal: 202.5,
    },
    {
      positie: 6,
      naam: "Jasper Kempers",
      aanwezig: 26,
      poulepunten: 76,
      winnaarsrondeLegsGewonnen: 64,
      winnaarsrondeLegsVerloren: 54,
      verliezersrondeLegsGewonnen: 26,
      verliezersrondeLegsVerloren: 8,
      hoogsteFinish: 157,
      aantal180s: 7,
      puntenTotaal: 200,
    },
    {
      positie: 7,
      naam: "Marco Thijssen",
      aanwezig: 34,
      poulepunten: 74,
      winnaarsrondeLegsGewonnen: 32,
      winnaarsrondeLegsVerloren: 49,
      verliezersrondeLegsGewonnen: 76,
      verliezersrondeLegsVerloren: 43,
      hoogsteFinish: 127,
      aantal180s: 9,
      puntenTotaal: 191,
    },
    {
      positie: 8,
      naam: "Willem Thijssen",
      aanwezig: 20,
      poulepunten: 80,
      winnaarsrondeLegsGewonnen: 77,
      winnaarsrondeLegsVerloren: 71,
      verliezersrondeLegsGewonnen: 0,
      verliezersrondeLegsVerloren: 0,
      hoogsteFinish: 132,
      aantal180s: 6,
      puntenTotaal: 190,
    },
    {
      positie: 9,
      naam: "Rocco Meerbeek",
      aanwezig: 34,
      poulepunten: 83,
      winnaarsrondeLegsGewonnen: 32,
      winnaarsrondeLegsVerloren: 59,
      verliezersrondeLegsGewonnen: 44,
      verliezersrondeLegsVerloren: 31,
      hoogsteFinish: 152,
      aantal180s: 6,
      puntenTotaal: 186,
    },
    {
      positie: 10,
      naam: "Luca Schopema",
      aanwezig: 14,
      poulepunten: 50,
      winnaarsrondeLegsGewonnen: 80,
      winnaarsrondeLegsVerloren: 59,
      verliezersrondeLegsGewonnen: 0,
      verliezersrondeLegsVerloren: 0,
      hoogsteFinish: 125,
      aantal180s: 7,
      puntenTotaal: 162,
    },
    {
      positie: 11,
      naam: "Raymond Horst",
      aanwezig: 19,
      poulepunten: 56,
      winnaarsrondeLegsGewonnen: 48,
      winnaarsrondeLegsVerloren: 44,
      verliezersrondeLegsGewonnen: 29,
      verliezersrondeLegsVerloren: 17,
      hoogsteFinish: 130,
      aantal180s: 11,
      puntenTotaal: 156.5,
    },
    {
      positie: 12,
      naam: "Mario v Til",
      aanwezig: 23,
      poulepunten: 72,
      winnaarsrondeLegsGewonnen: 32,
      winnaarsrondeLegsVerloren: 56,
      verliezersrondeLegsGewonnen: 27,
      verliezersrondeLegsVerloren: 17,
      hoogsteFinish: 127,
      aantal180s: 2,
      puntenTotaal: 152.5,
    },
    {
      positie: 13,
      naam: "Bob Smit",
      aanwezig: 11,
      poulepunten: 40,
      winnaarsrondeLegsGewonnen: 76,
      winnaarsrondeLegsVerloren: 43,
      verliezersrondeLegsGewonnen: 0,
      verliezersrondeLegsVerloren: 0,
      hoogsteFinish: 126,
      aantal180s: 10,
      puntenTotaal: 151,
    },
    {
      positie: 14,
      naam: "Dennis van het Hof",
      aanwezig: 31,
      poulepunten: 63,
      winnaarsrondeLegsGewonnen: 9,
      winnaarsrondeLegsVerloren: 30,
      verliezersrondeLegsGewonnen: 55,
      verliezersrondeLegsVerloren: 48,
      hoogsteFinish: 117,
      aantal180s: 9,
      puntenTotaal: 142.5,
    },
    {
      positie: 15,
      naam: "Eddy de Jode",
      aanwezig: 30,
      poulepunten: 60,
      winnaarsrondeLegsGewonnen: 17,
      winnaarsrondeLegsVerloren: 35,
      verliezersrondeLegsGewonnen: 47,
      verliezersrondeLegsVerloren: 34,
      hoogsteFinish: 100,
      aantal180s: 3,
      puntenTotaal: 135.5,
    },
    {
      positie: 16,
      naam: "Frans Spronk",
      aanwezig: 29,
      poulepunten: 59,
      winnaarsrondeLegsGewonnen: 7,
      winnaarsrondeLegsVerloren: 26,
      verliezersrondeLegsGewonnen: 53,
      verliezersrondeLegsVerloren: 46,
      hoogsteFinish: 114,
      aantal180s: 4,
      puntenTotaal: 128.5,
    },
    {
      positie: 17,
      naam: "Muppet",
      aanwezig: 29,
      poulepunten: 55,
      winnaarsrondeLegsGewonnen: 9,
      winnaarsrondeLegsVerloren: 27,
      verliezersrondeLegsGewonnen: 61,
      verliezersrondeLegsVerloren: 15,
      hoogsteFinish: 111,
      aantal180s: 2,
      puntenTotaal: 127.5,
    },
    {
      positie: 18,
      naam: "Timme Lensink",
      aanwezig: 24,
      poulepunten: 56,
      winnaarsrondeLegsGewonnen: 22,
      winnaarsrondeLegsVerloren: 35,
      verliezersrondeLegsGewonnen: 39,
      verliezersrondeLegsVerloren: 30,
      hoogsteFinish: 110,
      aantal180s: 3,
      puntenTotaal: 125.5,
    },
    {
      positie: 19,
      naam: "Erwin Smit",
      aanwezig: 27,
      poulepunten: 58,
      winnaarsrondeLegsGewonnen: 8,
      winnaarsrondeLegsVerloren: 31,
      verliezersrondeLegsGewonnen: 43,
      verliezersrondeLegsVerloren: 30,
      hoogsteFinish: 124,
      aantal180s: 1,
      puntenTotaal: 120.5,
    },
    {
      positie: 20,
      naam: "Gilliam Kempers",
      aanwezig: 39,
      poulepunten: 54,
      winnaarsrondeLegsGewonnen: 1,
      winnaarsrondeLegsVerloren: 9,
      verliezersrondeLegsGewonnen: 41,
      verliezersrondeLegsVerloren: 75,
      hoogsteFinish: 0,
      aantal180s: 0,
      puntenTotaal: 114.5,
    },
    {
      positie: 21,
      naam: "Adwin Gras",
      aanwezig: 13,
      poulepunten: 40,
      winnaarsrondeLegsGewonnen: 45,
      winnaarsrondeLegsVerloren: 39,
      verliezersrondeLegsGewonnen: 18,
      verliezersrondeLegsVerloren: 6,
      hoogsteFinish: 0,
      aantal180s: 1,
      puntenTotaal: 108,
    },
    {
      positie: 22,
      naam: "Rene Lippets",
      aanwezig: 18,
      poulepunten: 20,
      winnaarsrondeLegsGewonnen: 2,
      winnaarsrondeLegsVerloren: 9,
      verliezersrondeLegsGewonnen: 27,
      verliezersrondeLegsVerloren: 35,
      hoogsteFinish: 121,
      aantal180s: 2,
      puntenTotaal: 59.5,
    },
    {
      positie: 23,
      naam: "Sjangie Verbeuken",
      aanwezig: 9,
      poulepunten: 18,
      winnaarsrondeLegsGewonnen: 6,
      winnaarsrondeLegsVerloren: 13,
      verliezersrondeLegsGewonnen: 33,
      verliezersrondeLegsVerloren: 11,
      hoogsteFinish: 125,
      aantal180s: 4,
      puntenTotaal: 57.5,
    },
    {
      positie: 24,
      naam: "Mike Thijssen",
      aanwezig: 6,
      poulepunten: 18,
      winnaarsrondeLegsGewonnen: 25,
      winnaarsrondeLegsVerloren: 21,
      verliezersrondeLegsGewonnen: 0,
      verliezersrondeLegsVerloren: 0,
      hoogsteFinish: 137,
      aantal180s: 0,
      puntenTotaal: 55,
    },
    {
      positie: 25,
      naam: "Rick Hiddink",
      aanwezig: 7,
      poulepunten: 16,
      winnaarsrondeLegsGewonnen: 18,
      winnaarsrondeLegsVerloren: 17,
      verliezersrondeLegsGewonnen: 10,
      verliezersrondeLegsVerloren: 5,
      hoogsteFinish: 120,
      aantal180s: 1,
      puntenTotaal: 54,
    },
    {
      positie: 26,
      naam: "Ian Wagner",
      aanwezig: 17,
      poulepunten: 24,
      winnaarsrondeLegsGewonnen: 3,
      winnaarsrondeLegsVerloren: 9,
      verliezersrondeLegsGewonnen: 20,
      verliezersrondeLegsVerloren: 27,
      hoogsteFinish: 0,
      aantal180s: 0,
      puntenTotaal: 54,
    },
    {
      positie: 27,
      naam: "Henk Hubers",
      aanwezig: 17,
      poulepunten: 25,
      winnaarsrondeLegsGewonnen: 2,
      winnaarsrondeLegsVerloren: 9,
      verliezersrondeLegsGewonnen: 10,
      verliezersrondeLegsVerloren: 24,
      hoogsteFinish: 0,
      aantal180s: 0,
      puntenTotaal: 49,
    },
    {
      positie: 28,
      naam: "Bjorn Schoenakker",
      aanwezig: 7,
      poulepunten: 22,
      winnaarsrondeLegsGewonnen: 21,
      winnaarsrondeLegsVerloren: 25,
      verliezersrondeLegsGewonnen: 4,
      verliezersrondeLegsVerloren: 3,
      hoogsteFinish: 120,
      aantal180s: 2,
      puntenTotaal: 49,
    },
    {
      positie: 29,
      naam: "Daniel Spaink",
      aanwezig: 6,
      poulepunten: 11,
      winnaarsrondeLegsGewonnen: 7,
      winnaarsrondeLegsVerloren: 11,
      verliezersrondeLegsGewonnen: 7,
      verliezersrondeLegsVerloren: 7,
      hoogsteFinish: 0,
      aantal180s: 2,
      puntenTotaal: 29.5,
    },
    {
      positie: 30,
      naam: "Arno Vermeer",
      aanwezig: 9,
      poulepunten: 12,
      winnaarsrondeLegsGewonnen: 0,
      winnaarsrondeLegsVerloren: 6,
      verliezersrondeLegsGewonnen: 10,
      verliezersrondeLegsVerloren: 16,
      hoogsteFinish: 0,
      aantal180s: 0,
      puntenTotaal: 26,
    },
    {
      positie: 31,
      naam: "Sem Riethorst",
      aanwezig: 4,
      poulepunten: 6,
      winnaarsrondeLegsGewonnen: 1,
      winnaarsrondeLegsVerloren: 3,
      verliezersrondeLegsGewonnen: 4,
      verliezersrondeLegsVerloren: 8,
      hoogsteFinish: 0,
      aantal180s: 0,
      puntenTotaal: 13,
    },
    {
      positie: 32,
      naam: "Johan Zaaijer",
      aanwezig: 1,
      poulepunten: 1,
      winnaarsrondeLegsGewonnen: 0,
      winnaarsrondeLegsVerloren: 0,
      verliezersrondeLegsGewonnen: 1,
      verliezersrondeLegsVerloren: 2,
      hoogsteFinish: 0,
      aantal180s: 0,
      puntenTotaal: 2.5,
    },
  ],
};

const TUSSENSTANDEN: HistorischeTussenstand[] = [OFFICIELE_TUSSENSTAND_2025_2026];

export function haalHistorischeTussenstand(
  seizoenId: string
): HistorischeTussenstand | null {
  return TUSSENSTANDEN.find((t) => t.seizoen === seizoenId) ?? null;
}

/** Officiële rij van één speler, of null als die niet op de foto staat. */
export function haalHistorischeSpeler(
  seizoenId: string,
  naam: string
): HistorischeSpelerStand | null {
  const tussenstand = haalHistorischeTussenstand(seizoenId);
  if (!tussenstand) return null;
  return tussenstand.spelers.find((s) => namenZijnGelijk(s.naam, naam)) ?? null;
}

export function historischeSpelerAlsMap(
  tussenstand: HistorischeTussenstand
): Map<string, HistorischeSpelerStand> {
  return new Map(tussenstand.spelers.map((s) => [s.naam, s]));
}

/** Avonden op of vóór de snapshot-datum zitten al in de officiële stand. */
export function isAvondNaTussenstand(
  avondDatum: string,
  snapshotDatum: string
): boolean {
  if (!avondDatum) return true;
  const avond = new Date(avondDatum);
  if (Number.isNaN(avond.getTime())) return true;

  const snapshotEinde = new Date(`${snapshotDatum}T23:59:59.999`);
  return avond.getTime() > snapshotEinde.getTime();
}
