export const CLUB_LEDEN = [
  "John Wolsheumer",
  "Nico Pas",
  "Toon te Kamp",
  "Ronnie Kijvekamp",
  "Jasper Kempers",
  "Marco Thijssen",
  "Rinaldo Lenting",
  "Rocco Meerbeek",
  "Willem Thijssen",
  "Raymond Horst",
  "Mario v Til",
  "Ervin Smit",
  "Bob Smit",
  "Eddy de Jode",
  "Muppet",
  "Dennis van het Hof",
  "Advin Gras",
  "Luca Schopema",
  "Frans Spronk",
  "Timme Jensink",
  "Gilliam Kempers",
  "Ryan Meerbeek",
  "Erik van Rhijn",
  "Rene Lippets",
  "Mike Thijssen",
  "Rick Hiddink",
  "Sjangie Verbeuken",
  "Ian Wagner",
  "Henk Hubers",
  "Arno Vermeer",
  "Daniel Spaink",
] as const;

export type LidNaam = (typeof CLUB_LEDEN)[number];
